---
- name: Check that all nodes can perform password-free ssh logins as root
  ansible.builtin.command: >-
    ssh {{ item }} hostname
  register: int_reg_ssh_results
  loop: "{{ ansible_play_hosts }}"
  changed_when: false
  failed_when: false
  check_mode: false # always run

- name: Assert that all hosts can perform password-free ssh logins as root
  ansible.builtin.assert:
    that: >-
      {{ item.rc }} == 0
    fail_msg: >-
      {{ inventory_hostname }} was not not able to create an ssh connection to
      {{ item.item }}. Ensure that all hosts can ssh to each other as root when
      running this role. Consider using the ssh-key-prep role to achieve this.
    success_msg: >-
      {{ inventory_hostname }} was able to create an ssh connection to
      {{ item.item }}.
  loop: "{{ int_reg_ssh_results.results }}"
