- name: Assert that hana_side and hana_instance_number are defined
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: >-
      The variable {{ item }} is not defined. Ensure this variable is populated
      when running this role.
    success_msg: >-
      The variable {{ item }} is defined
  check_mode: false
  loop:
    - hana_sid
    - hana_instance_number

- name: Check hana_sid is compliant
  ansible.builtin.assert:
    that:
      hana_sid is ansible.builtin.regex('[A-Z]{1}[A-Z0-9]{2}')
    fail_msg: >-
      hana_sid must consist of three characters. Characters must be
      uppercase alphabetical characters or numbers only. The character must be
      an alphabetical character.
    success_msg: >-
      hana_sid matches the required pattern.
  # Always run, even in check mode
  check_mode: false

- name: Ensure that hana_sid is not a reserved SID name
  ansible.builtin.assert:
    that:
      hana_sid not in int_var_reserved_sids
    fail_msg: >-
      hana_sid is set to {{ hana_sid }}, this is a reserved SID and cannot be
      used.  Change the variable hana_sid to an allowed value.
    success_msg: >-
      hana_sid is not a reserved value
  # Always run, even in check mode
  check_mode: false

- name: Ensure that HANA instance number is compliant
  ansible.builtin.assert:
    that:
      hana_instance_number is ansible.builtin.regex('^[0-9]{2}$')
    fail_msg: >-
      hana_instance_number is set to {{ hana_instance_number }}, which is not
      compliant. hana_instance_number must be a composed of two numerical
      digits, for example '00'.
    success_msg: >-
      hana_instance_number is an allowed value.
  # Always run, even in check mode
  check_mode: false
