---
- name: Ensure that HANA sar file is unpacked
  ansible.builtin.command:
    "{{ sapcar_binary }} -xf {{ hana_sar }} -R {{ hana_unpack_directory }} -manifest SIGNATURE.SMF"
  when: not int_fact_hana_unpacked

- name: Copy manifest file
  ansible.builtin.copy:
    src: "{{ hana_unpack_directory }}//{{ int_var_manifest_filename }}"
    remote_src: true
    dest: "{{ hana_unpack_directory }}/{{ int_var_hana_unpack_name }}/{{ int_var_manifest_filename }}"
    owner: "root"
    group: "root"
    mode: "0600"
  when: not int_fact_hana_unpacked

- name: Remove original manifest file
  ansible.builtin.file:
    path: "{{ hana_unpack_directory }}//{{ int_var_manifest_filename }}"
    state: absent
  when: not int_fact_hana_unpacked

- name: Populate installation template
  ansible.builtin.template:
    owner: "root"
    group: "root"
    mode: "0600"
    src: templates/hana_install.j2
    dest: "/tmp/hana_install"

- name: Ensure HANA is installed
  ansible.builtin.command:
    "{{ hana_unpack_directory }}/{{ int_var_hana_unpack_name }}/hdblcm --batch --configfile=/tmp/hana_install"
  when: not int_fact_hana_installed
