int_var_reserved_sids:
  - "ADD"
  - "ALL"
  - "AMD"
  - "AND"
  - "ANY"
  - "ARE"
  - "ASC"
  - "AUX"
  - "AVG"
  - "BIT"
  - "CDC"
  - "COM"
  - "CON"
  - "DBA"
  - "END"
  - "EPS"
  - "FOR"
  - "GET"
  - "GID"
  - "IBM"
  - "INT"
  - "KEY"
  - "LOG"
  - "LPT"
  - "MAP"
  - "MAX"
  - "MIN"
  - "MON"
  - "NIX"
  - "NOT"
  - "NUL"
  - "OFF"
  - "OLD"
  - "OMS"
  - "OUT"
  - "PAD"
  - "PRN"
  - "RAW"
  - "REF"
  - "ROW"
  - "SAP"
  - "SET"
  - "SGA"
  - "SHG"
  - "SID"
  - "SQL"
  - "SUM"
  - "SYS"
  - "TMP"
  - "TOP"
  - "UID"
  - "USE"
  - "USR"
  - "VAR"
