---
- name: Use sles_register role
  hosts: all
  remote_user: my_ansible_user
  become: true
  vars:
    hana_sid: 'SU1'
    hana_instance_number: '00'
    hana_systemdb_password: 'Example_poor_passwo0rd'
    hana_system_replication_nodes:
      - hostname: 'hana01'
        ip_address: '10.10.10.10'
        role: 'primary'
        site: 'Node01'
      - hostname: 'hana02'
        ip_address: '10.10.10.11'
        role: 'secondary'
        site: 'Node02'
    hsr_replication_mode: 'sync'

  roles:
    - { role: ../roles/hana-system-replication }
