---
- name: Create random strings for temporary files
  ansible.builtin.set_fact:
    int_fact_tmp_backup_query_file: "/tmp/ansible_{{ lookup('community.general.random_string', length=12, special=false) }}"
    int_fact_tmp_results_file: "/tmp/ansible_{{ lookup('community.general.random_string', length=12, special=false) }}"
    int_fact_tmp_backup_command_file: "/tmp/ansible_{{ lookup('community.general.random_string', length=12, special=false) }}"
  when: backup_needed

# It's really important that the temporary files are destroyed even if some
# tasks fail. For that reason the following commands are in a block which has an
# always
- name: Backup
  when: backup_needed and not ansible_check_mode
  block:
    - name: Ensure all tenants query is copied to remote hosts
      ansible.builtin.copy:
        owner: root
        group: root
        mode: '0600'
        src: files/all_tenants_query.sql
        dest: "{{ int_fact_tmp_backup_query_file }}"
      # although a file is being written to the host, it is ephemeral as it
      # always removed, even if tasks in the block fail. Therefore, the authors
      # do not consider writing this file as changing the system configuration
      # the same is true of the delete operations for these temporary files
      changed_when: false


    - name: Retrieve a list of database tenants for backup
      ansible.builtin.command: >-
        {{ int_var_hdbsql_path }} {{ int_var_hdbsql_args }} -I {{ int_fact_tmp_backup_query_file }} -o {{ int_fact_tmp_results_file }}
      # Again, hdbsql is only selecting from monitoring tables and reading and
      # writing to files that are ephemeral, therefore these DB operation are
      # not considered to be changes
      changed_when: false
      no_log: true

    # It's not ideal to use command and cat like this, but the alternative is to
    # copy the remote files back to the controller which is probably a worse
    # solution
    - name: Read tenant file
      ansible.builtin.command: "cat {{ int_fact_tmp_results_file }}"
      register: int_reg_tenant_list
      changed_when: false

    - name: Set fact for database tenant names
      ansible.builtin.set_fact:
        int_fact_db_tenant_names: "{{ int_reg_tenant_list.stdout | split('\n') }}"

    - name: Prepare initial default backup SQL statement to backup all tenants
      ansible.builtin.template:
        dest: "{{ int_fact_tmp_backup_command_file }}"
        src: templates/initial_backup.j2
        owner: root
        group: root
        mode: '0600'
      changed_when: false

    # Need to set a when condition!
    - name: Run backups
      ansible.builtin.command: >-
        {{ int_var_hdbsql_path }} {{ int_var_hdbsql_args }} -I {{ int_fact_tmp_backup_command_file }}
      # The task will only run when a backup is needed due to the block when
      # condition, but to solve a linting error it is required to repeat it
      # here.
      when: backup_needed
      no_log: true

  always:
    # Unfortunately, you can't currently use loops within blocks, so we'll need
    # to remove each temporary file with it's one module call
    - name: Remove temporary backup query file
      ansible.builtin.file:
        path: "{{ int_fact_tmp_backup_query_file }}"
        state: absent
      changed_when: false

    - name: Remove temporary backup command result file
      ansible.builtin.file:
        path: "{{ int_fact_tmp_results_file }}"
        state: absent
      changed_when: false

    - name: Remove temporary backup command file
      ansible.builtin.file:
        path: "{{ int_fact_tmp_backup_command_file }}"
        state: absent
      changed_when: false

- name: Set backup_needed fact to false
  ansible.builtin.set_fact:
    backup_needed: "{{ false | bool }}"
  when: not ansible_check_mode
